//MEMBUAT FUNGSI YANG MENERIMA 1 INPUT BERUPA ANGKA DENGAN MENGEMBALIKAN STRING APAKAH ANGKA YANG DIMASUKKAN ADALAH 
//BILANGAN POSITIF ATAU BILANGAN NEGATIF

function Num (angka){
    if (angka <= 0) {
        return "BILANGAN YANG DIINPUT ADALAH BILANGAN NEGATIF";
    } else {
        return "BILANGAN YANG DIINPUT ADALAH BILANGAN POSITIF";
    }

}

let output = Num(1000);
console.log(output);